version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  target-branch: development
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  cooldown:
    default-days: 7
    exclude:
    - codeinwp/themeisle-sdk
